name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build Android APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Install Expo CLI
        run: npm install -g expo-cli

      - name: EAS login
        run: npx eas-cli login --token ${{ secrets.EAS_TOKEN }}

      - name: Build APK
        run: npx eas build --platform android --profile preview --non-interactive

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: app-apk
          path: dist/**/*.apk
